/**
 * A looping town theme, composed here rather than sampled.
 *
 * Every note is generated by oscillators at runtime. Nothing is downloaded and
 * no recording is embedded — the music this is dressed as is somebody else's
 * property, and a sixteen-bar tune written in code is not. It also costs zero
 * bytes of bundle, which matters more than usual for an app that has to load
 * at a climbing wall on gym wifi.
 *
 * Deliberately off by default. Browsers block autoplay anyway, but the real
 * reason is that a tool a coach opens mid-session should not start singing at
 * them in a public gym.
 */
const STORAGE_KEY = 'sendlog.music'

/** Semitone offsets from A4, as a plain major-key melody in C. */
const MELODY: [number, number][] = [
  // [semitone from A4, beats] — a bright, stepwise tune that resolves home.
  [3, 1], [7, 1], [10, 1], [12, 1], [10, 1], [7, 1], [8, 2],
  [5, 1], [8, 1], [12, 1], [15, 1], [12, 1], [8, 1], [7, 2],
  [3, 1], [7, 1], [10, 1], [15, 1], [14, 1], [10, 1], [12, 2],
  [10, 1], [7, 1], [5, 1], [3, 1], [5, 1], [7, 1], [3, 2],
]

/** A walking bass under it, one note per two beats. */
const BASS: [number, number][] = [
  [-9, 2], [-2, 2], [-4, 2], [-9, 2],
  [-7, 2], [-2, 2], [-9, 2], [-5, 2],
  [-9, 2], [-2, 2], [-4, 2], [-7, 2],
  [-5, 2], [-4, 2], [-7, 2], [-9, 2],
]

const BPM = 132
const BEAT = 60 / BPM
const hz = (semitonesFromA4: number) => 440 * Math.pow(2, semitonesFromA4 / 12)

let ctx: AudioContext | null = null
let master: GainNode | null = null
let timer: number | null = null
let playing = false
/** Set while the alarm or a shout is speaking, so the tune gets out of the way. */
let ducked = false

export const musicEnabled = (): boolean => {
  try {
    return localStorage.getItem(STORAGE_KEY) === 'on'
  } catch {
    return false
  }
}

const remember = (on: boolean) => {
  try {
    localStorage.setItem(STORAGE_KEY, on ? 'on' : 'off')
  } catch {
    /* storage blocked — the preference just won't survive this page view */
  }
}

function note(
  at: number,
  freq: number,
  beats: number,
  type: OscillatorType,
  peak: number,
): void {
  if (!ctx || !master) return
  const osc = ctx.createOscillator()
  const gain = ctx.createGain()
  osc.type = type
  osc.frequency.value = freq
  const dur = beats * BEAT
  // A short pluck envelope: chip voices have no sustain to speak of, and a
  // flat gate would click at both ends.
  gain.gain.setValueAtTime(0.0001, at)
  gain.gain.exponentialRampToValueAtTime(peak, at + 0.012)
  gain.gain.exponentialRampToValueAtTime(0.0001, at + dur * 0.92)
  osc.connect(gain).connect(master)
  osc.start(at)
  osc.stop(at + dur)
}

/** Schedule one pass of the loop starting at `from`, and return its length. */
function scheduleLoop(from: number): number {
  let t = from
  for (const [semi, beats] of MELODY) {
    note(t, hz(semi), beats, 'square', 0.055)
    t += beats * BEAT
  }
  const barsLength = t - from
  let b = from
  for (const [semi, beats] of BASS) {
    note(b, hz(semi), beats, 'triangle', 0.075)
    b += beats * BEAT
  }
  return barsLength
}

function pump(): void {
  if (!ctx || !playing) return
  const len = scheduleLoop(ctx.currentTime + 0.05)
  // Re-arm a little before the loop ends so the seam is inaudible.
  timer = window.setTimeout(pump, Math.max(200, (len - 0.15) * 1000))
}

export function startMusic(): void {
  if (playing) return
  try {
    const Ctor =
      window.AudioContext ??
      (window as unknown as { webkitAudioContext?: typeof AudioContext }).webkitAudioContext
    if (!Ctor) return
    ctx ??= new Ctor()
    if (ctx.state === 'suspended') void ctx.resume()
    master ??= ctx.createGain()
    master.gain.value = ducked ? 0 : 1
    master.connect(ctx.destination)
    playing = true
    pump()
  } catch {
    playing = false
  }
}

export function stopMusic(): void {
  playing = false
  if (timer !== null) {
    window.clearTimeout(timer)
    timer = null
  }
  try {
    master?.disconnect()
  } catch {
    /* already gone */
  }
  master = null
}

export function setMusicEnabled(on: boolean): void {
  remember(on)
  if (on) startMusic()
  else stopMusic()
}

/**
 * Silence the tune without stopping it, for the seconds an alarm is ringing or
 * a shout is being spoken. Those two carry information; the music does not,
 * and two voices at once in a loud gym means neither is heard.
 */
export function duckMusic(ms = 2200): void {
  ducked = true
  if (master && ctx) {
    master.gain.cancelScheduledValues(ctx.currentTime)
    master.gain.setValueAtTime(0.0001, ctx.currentTime)
  }
  window.setTimeout(() => {
    ducked = false
    if (master && ctx && playing) {
      master.gain.exponentialRampToValueAtTime(1, ctx.currentTime + 0.4)
    }
  }, ms)
}

/**
 * Stop while the tab is hidden. A backgrounded chiptune is a battery drain in
 * somebody's pocket, and a phone that sings from inside a bag is worse.
 */
export function watchVisibility(): () => void {
  const onChange = () => {
    if (document.visibilityState === 'hidden') stopMusic()
    else if (musicEnabled()) startMusic()
  }
  document.addEventListener('visibilitychange', onChange)
  return () => document.removeEventListener('visibilitychange', onChange)
}
